context.properties = {
    default.clock.rate = 48000
    default.clock.quantum = 1024
    default.clock.min-quantum = 512
    default.clock.max-quantum = 2048
    default.clock.power-of-two-quantum = true
    support.node.latency = true
    resample.quality = 5
}

stream.properties = {
    node.autoconnect = true
}
