# Оптимизация памяти для игр и мультимедиа
vm.swappiness=100
vm.vfs_cache_pressure=50
vm.page-cluster=0

# Оптимизация ядра в рантайме
kernel.split_lock_mitigate=0
kernel.nmi_watchdog=0

# Улучшение сетевой производительности для онлайн-игр
net.core.netdev_max_backlog=32768
net.core.default_qdisc=fq_codel
net.ipv4.ip_local_port_range=1024 65000
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_notsent_lowat=16384
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fin_timeout=30

# Оптимизация для Btrfs и SSD
vm.dirty_background_bytes=67108864  # 1/4 от vm.dirty_bytes
vm.dirty_bytes=268435456            # пропускная способность SSD
vm.dirty_expire_centisecs=1300      # 13 секунд и вызов записи грязных страниц
vm.dirty_writeback_centisecs=100    # 1 секунд между периодами работы потоков по гразным страницам
