# Оптимизированный ~/.makepkg.conf
# Используем все доступные ядра процессора
MAKEFLAGS="-j16"

# Оптимизации для компилятора
CFLAGS="-march=native -mtune=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fuse-ld=gold"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
RUSTFLAGS="-C opt-level=3 -C target-cpu=native -C codegen-units=1 -C link-arg=-z -C link-arg=pack-relative-relocs"

# Оптимизация для линковщика
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

# Использование ccache для ускорения повторных сборок
BUILDENV=(!distcc color !ccache check !sign)

# Сжатие пакетов
COMPRESSZST=(zstd -c -z -q -T0 -5 -)
COMPRESSXZ=(xz -c -z --threads=16 -)

# Использование tmpfs для сборки (если достаточно RAM)
BUILDDIR=/var/tmp/makepkg

# Отключение дебаг-символов для уменьшения размера пакетов
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)
