# Параметры PCIe
options nvidia NVreg_UsePageAttributeTable=1 NVreg_EnableResizableBar=1

# Управление питанием (умеренный режим)
options nvidia NVreg_DynamicPowerManagement=0x01

# Параметры производительности
options nvidia NVreg_ResmanDebugLevel=0 NVreg_PreserveVideoMemoryAllocations=0
